version: '3.8'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: TransactionTable-app
    restart: no
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: tr-app-nginx
    restart: no
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    container_name: TR_mySQL
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306